server:
  port: 8201
  servlet:
    contextPath: /momoubin

spring:
  application:
    name: momoubin-business2-server  # 应用名称，在 Eureka 中作为 id 标识

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka  # EurekaServer 的地址，现在是自己的地址，如果是集群，需要加上其它 Server 的地址
  server:
    enable-self-preservation: false       # 关闭自我保护模式, 默认为打开
    eviction-interval-timer-in-ms: 5000   # 续期时间，即扫描失效服务的间隔时间
