server:
  port: 8100

spring:
  application:
    name: momoubin-gateway-server  # 应用名称，在 Eureka 中作为 id 标识
  cloud:
    gateway:
      routes:
        # 路由 id 随便写
        - id: business-server
          # 服务路径
          uri: http://localhost:8200
          # 匹配来自HTTP请求
          predicates:
          - Path=/mmb/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka  # EurekaServer 的地址，现在是自己的地址，如果是集群，需要加上其它 Server 的地址
  server:
    enable-self-preservation: false       # 关闭自我保护模式, 默认为打开
    eviction-interval-timer-in-ms: 5000   # 续期时间，即扫描失效服务的间隔时间